### ISSUE TITLE
Integration with GoReleaser

### ISSUE THREAD

**Issue by renanbastos93** [renanbastos93/alertcovid19#4]
We can create integration with [GoReleaser](https://goreleaser.com/) to generate packages to all platforms.

**Comment by cyruzin** [comment]
I see that the project already has this file, did you implemented it?

**Comment by renanbastos93** [comment]
Hi @cyruzin 

Thanks for your comment here.

Well, I implemented but I have a small problem don't know build to the window using `Goreleaser` and I wish added in the pipeline from actions to running Goreleaser each tag created.

**Comment by cyruzin** [comment]
I'll take a look.

**Comment by cyruzin** [comment]
Take a look: https://github.com/renanbastos93/alertcovid19/pull/13

**Comment by cyruzin** [comment]
To deploy to you repo, check this action: https://github.com/goreleaser/goreleaser-action

**Comment by renanbastos93** [comment]
Thanks a lot, I will see your pull request.
